#!/usr/bin/env node
/**
 * OpenAPI -> TypeScript codegen.
 *
 * Reads every YAML/JSON spec under contracts/api/<engine>/*.{yaml,yml,json}
 * and emits a per-engine TS file under src/lib/api/generated/<engine>.ts
 * containing the operations + schemas as TS types. The generated client is
 * then a thin Zod-validated wrapper on top (Constitution: hand-written
 * clients are forbidden).
 */
import { readdirSync, mkdirSync, existsSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const here = path.dirname(fileURLToPath(import.meta.url));
const contractsRoot = path.resolve(here, "..", "contracts", "api");
const outRoot = path.resolve(here, "..", "src", "lib", "api", "generated");

if (!existsSync(contractsRoot)) {
    console.warn(`[codegen] contracts/api/ not found at ${contractsRoot}`);
    process.exit(0);
}

mkdirSync(outRoot, { recursive: true });

const engineDirs = readdirSync(contractsRoot, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name);

if (engineDirs.length === 0) {
    console.log("[codegen] no engine directories under contracts/api/");
    process.exit(0);
}

for (const engine of engineDirs) {
    const engineDir = path.join(contractsRoot, engine);
    const specs = readdirSync(engineDir).filter((f) =>
        /\.(ya?ml|json)$/i.test(f),
    );
    if (specs.length === 0) continue;

    const chunks = [];
    for (const spec of specs) {
        const absolute = path.join(engineDir, spec);
        const ast = await openapiTS(new URL(`file://${absolute}`));
        chunks.push(`// from ${path.relative(here, absolute)}`);
        chunks.push(astToString(ast));
    }

    const outPath = path.join(outRoot, `${engine}.ts`);
    await writeFile(
        outPath,
        `/* eslint-disable */\n// AUTO-GENERATED by scripts/codegen-api.mjs — DO NOT EDIT.\n\n${chunks.join("\n\n")}\n`,
    );
    console.log(`[codegen] wrote ${path.relative(here, outPath)}`);
}
